swagger: "2.0"
info: {}
basePath: /v1
paths:
  /category/:
    get:
      tags:
      - category
      description: Get category
      operationId: CategoryController.Get category
      responses:
        "200":
          description: string
        "400":
          description: string
  /food/:
    get:
      tags:
      - food
      description: Get food
      operationId: FoodController.Get food
      responses:
        "200":
          description: string
        "400":
          description: string
    put:
      tags:
      - food
      description: Put
      operationId: FoodController.Put food
      parameters:
      - in: body
        name: body
        description: food
        required: true
        schema:
          $ref: '#/definitions/models.Food'
      responses:
        "200":
          description: string
        "400":
          description: string
    post:
      tags:
      - food
      description: Post
      operationId: FoodController.Post food
      parameters:
      - in: body
        name: body
        description: food
        required: true
        schema:
          $ref: '#/definitions/models.Food'
      responses:
        "200":
          description: string
        "400":
          description: string
  /food/{id}:
    delete:
      tags:
      - food
      description: Put
      operationId: FoodController.Detele food
      parameters:
      - in: path
        name: id
        description: food id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: string
        "400":
          description: string
  /menu/:
    get:
      tags:
      - menu
      description: Get menu
      operationId: MenuController.Get menu
      responses:
        "200":
          description: string
        "400":
          description: string
    post:
      tags:
      - menu
      description: Post
      operationId: MenuController.Post menu
      parameters:
      - in: body
        name: body
        description: menu
        required: true
        schema:
          $ref: '#/definitions/models.Menu'
      responses:
        "200":
          description: string
        "400":
          description: string
  /menu/detail:
    get:
      tags:
      - menu
      description: Get detail menu
      operationId: MenuController.Get detail menu
      responses:
        "200":
          description: string
        "400":
          description: string
  /statisticstore/:
    get:
      tags:
      - statisticstore
      summary: '"Get thống kê một cửa hàng"'
      description: Get Statictic Store
      operationId: StatisticStoreController.Get Statictic Store
      parameters:
      - in: query
        name: sid
        description: store id
        required: true
        type: integer
        format: int64
      - in: query
        name: startTime
        description: start time
        type: integer
        format: int64
      - in: query
        name: endTime
        description: end time
        type: integer
        format: int64
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResStatisticStore'
        "404":
          description: responses.ResStatisticStore
  /store/:
    get:
      tags:
      - store
      description: Get
      operationId: StoreController.Get
      responses:
        "200":
          description: string
        "400":
          description: string
  /store/comment:
    get:
      tags:
      - store
      description: Comment
      operationId: StoreController.Comment
      responses:
        "200":
          description: string
        "400":
          description: string
definitions:
  models.BestSellingFoods:
    title: BestSellingFoods
    type: object
    properties:
      food_id:
        type: string
      food_name:
        type: string
      total_count:
        type: string
  models.Food:
    title: Food
    type: object
    properties:
      category_id:
        type: integer
        format: int64
      content:
        type: string
      create_date:
        type: integer
        format: int64
      id:
        type: integer
        format: int64
      image:
        type: string
      init_price:
        type: string
      menu_id:
        type: integer
        format: int64
      name:
        type: string
      sale_price:
        type: string
      status:
        type: integer
        format: int64
      store_id:
        type: integer
        format: int64
      title:
        type: string
      update_date:
        type: integer
        format: int64
  models.LoyalCustomers:
    title: LoyalCustomers
    type: object
    properties:
      customers_id:
        type: string
      customers_name:
        type: string
      total_count:
        type: string
  models.Menu:
    title: Menu
    type: object
    properties:
      create_date:
        type: integer
        format: int64
      id:
        type: integer
        format: int64
      name:
        type: string
      store_id:
        type: integer
        format: int64
      update_date:
        type: integer
        format: int64
  models.Statistic:
    title: Statistic
    type: object
    properties:
      Revenue:
        type: string
      StatisticAllStore:
        type: array
        items:
          $ref: '#/definitions/models.StatisticStore'
      TotalCustomer:
        type: string
      TotalShipper:
        type: string
      TotalShop:
        type: string
  models.StatisticStore:
    title: StatisticStore
    type: object
    properties:
      best_selling_foods:
        type: array
        items:
          $ref: '#/definitions/models.BestSellingFoods'
      id:
        type: string
      loyal_customers_name:
        type: array
        items:
          $ref: '#/definitions/models.LoyalCustomers'
      name:
        type: string
      number_of_orders:
        type: string
      rate_avg:
        type: string
      revenue:
        type: string
  responses.Err:
    title: Err
    type: object
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  responses.ResStatistic:
    title: ResStatistic
    type: object
    properties:
      data:
        $ref: '#/definitions/models.Statistic'
      error:
        $ref: '#/definitions/responses.Err'
  responses.ResStatisticStore:
    title: ResStatisticStore
    type: object
    properties:
      data:
        $ref: '#/definitions/models.StatisticStore'
      error:
        $ref: '#/definitions/responses.Err'
